### PR TITLE
Started with Tina's last clean copy, will add logo element back in future pushes

### PR DESCRIPTION
**Pull request by tsoloist**
Master clone had alignment issues with dropdowns, search field code didn't work, and had extraneous files, so I started with Tina's last working copy which was free from those issues. I also added comments to each section.

### CODE REVIEW

**Review by cherielum — APPROVED** [review]
Ok.

**Review by cherielum — APPROVED** [review]

**Review by cherielum — APPROVED** [review]

**Review by cherielum — APPROVED** [review]
good.

**Review by cherielum — APPROVED** [review]
Yes

**Review by cherielum — APPROVED** [review]
Great

**Comment by ConsultAtlas** [comment]
I am not sure how to resolve the conflicts

**Pull request merged**
